name: pocket_business_calculator
description: A simple, modern business calculator built with Flutter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
flutter_launcher_icons:
  android: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21